#! /usr/bin/env bash
set -x
set -e

AWS_CONFIG_FILE=$HOME/.aws/config

touch $AWS_CONFIG_FILE
chmod 600 $AWS_CONFIG_FILE

echo "[profile cli]"                                > $AWS_CONFIG_FILE
echo "aws_access_key_id=$AWS_ACCESS_KEY_ID"         >> $AWS_CONFIG_FILE
echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> $AWS_CONFIG_FILE


eb setenv \
  AWS_PROFILE=$AWS_PROFILE \
  AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
  AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
  AWS_REGION=$AWS_REGION \
  AWS_BUCKET=$AWS_BUCKET \
  PGPORT=$PGPORT \
  PORT=$PORT \
  POSTGRES_DB=$POSTGRES_DB \
  POSTGRES_HOST=$POSTGRES_HOST \
  POSTGRES_PASSWORD=$POSTGRES_PASSWORD \
  POSTGRES_USERNAME=$POSTGRES_USERNAME \
  URL=$URL

eb deploy
